/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nayansaxena
 */
public class Food_Locality extends javax.swing.JFrame {

    /**
     * Creates new form Food_Locality
     */
    public Food_Locality() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        food_oldcity = new javax.swing.JButton();
        food_mpnagar = new javax.swing.JButton();
        food_gulmohar = new javax.swing.JButton();
        food_10no = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/location.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        food_oldcity.setToolTipText("");
        food_oldcity.setAlignmentY(0.0F);
        food_oldcity.setBorderPainted(false);
        food_oldcity.setContentAreaFilled(false);
        food_oldcity.setFocusPainted(false);
        food_oldcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_oldcityActionPerformed(evt);
            }
        });
        getContentPane().add(food_oldcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 390, 170));

        food_mpnagar.setToolTipText("");
        food_mpnagar.setAlignmentY(0.0F);
        food_mpnagar.setBorderPainted(false);
        food_mpnagar.setContentAreaFilled(false);
        food_mpnagar.setFocusPainted(false);
        food_mpnagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_mpnagarActionPerformed(evt);
            }
        });
        getContentPane().add(food_mpnagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 170));

        food_gulmohar.setToolTipText("");
        food_gulmohar.setAlignmentY(0.0F);
        food_gulmohar.setBorderPainted(false);
        food_gulmohar.setContentAreaFilled(false);
        food_gulmohar.setFocusPainted(false);
        food_gulmohar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_gulmoharActionPerformed(evt);
            }
        });
        getContentPane().add(food_gulmohar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 410, 180));

        food_10no.setToolTipText("");
        food_10no.setAlignmentY(0.0F);
        food_10no.setBorderPainted(false);
        food_10no.setContentAreaFilled(false);
        food_10no.setFocusPainted(false);
        food_10no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_10noActionPerformed(evt);
            }
        });
        getContentPane().add(food_10no, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 420, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void food_oldcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_oldcityActionPerformed
        // TODO add your handling code here:
    Oldcityfood  Oldcityfood = new  Oldcityfood();
    Food_Locality.this.setVisible(false);
    Oldcityfood.setVisible(true);
    
        

    }//GEN-LAST:event_food_oldcityActionPerformed

    private void food_mpnagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_mpnagarActionPerformed
        // TODO add your handling code here:
        mpnagfood  mpnagfood = new  mpnagfood();
    Food_Locality.this.setVisible(false);
    mpnagfood.setVisible(true);
    }//GEN-LAST:event_food_mpnagarActionPerformed

    private void food_gulmoharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_gulmoharActionPerformed
        // TODO add your handling code here:
        gulmoharfood  gulmoharfood = new  gulmoharfood();
    Food_Locality.this.setVisible(false);
    gulmoharfood.setVisible(true);
    }//GEN-LAST:event_food_gulmoharActionPerformed

    private void food_10noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_10noActionPerformed
        // TODO add your handling code here:
        dusnofood  dusnofood = new  dusnofood();
    Food_Locality.this.setVisible(false);
    dusnofood.setVisible(true);
    }//GEN-LAST:event_food_10noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food_Locality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton food_10no;
    private javax.swing.JButton food_gulmohar;
    private javax.swing.JButton food_mpnagar;
    private javax.swing.JButton food_oldcity;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
