/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author nayansaxena
 */
public class gulmoharfood extends javax.swing.JFrame {

    /**
     * Creates new form gulmoharfood
     */
    public String control = null;
    public gulmoharfood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informationdialogbox = new javax.swing.JDialog();
        cf2 = new javax.swing.JLabel();
        phno = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        ratings = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cafekultur = new javax.swing.JButton();
        rollsmania = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bombaystrtcafe = new javax.swing.JButton();
        chocolady = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        subway = new javax.swing.JButton();
        sevencourse = new javax.swing.JButton();
        settingbutton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        chocoladi = new javax.swing.JLabel();
        rollsmania1 = new javax.swing.JButton();

        Informationdialogbox.setBounds(new java.awt.Rectangle(896, 0, 896, 470));
        Informationdialogbox.setResizable(false);
        Informationdialogbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InformationdialogboxFocusGained(evt);
            }
        });
        Informationdialogbox.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cf2.setFont(new java.awt.Font("Helvetica", 0, 36)); // NOI18N
        cf2.setForeground(new java.awt.Color(255, 255, 255));
        cf2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cf2.setMaximumSize(new java.awt.Dimension(340, 80));
        cf2.setMinimumSize(new java.awt.Dimension(340, 80));
        cf2.setPreferredSize(new java.awt.Dimension(340, 80));
        Informationdialogbox.getContentPane().add(cf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 340, 80));

        phno.setFont(new java.awt.Font("Helvetica", 0, 36)); // NOI18N
        phno.setForeground(new java.awt.Color(255, 255, 255));
        phno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phno.setMaximumSize(new java.awt.Dimension(340, 80));
        phno.setMinimumSize(new java.awt.Dimension(340, 80));
        phno.setPreferredSize(new java.awt.Dimension(340, 80));
        Informationdialogbox.getContentPane().add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 380, 80));

        address.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        address.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        address.setMaximumSize(new java.awt.Dimension(430, 110));
        address.setMinimumSize(new java.awt.Dimension(430, 110));
        address.setPreferredSize(new java.awt.Dimension(430, 110));
        Informationdialogbox.getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 390, 100));

        ratings.setFont(new java.awt.Font("Helvetica", 0, 36)); // NOI18N
        ratings.setForeground(new java.awt.Color(255, 255, 255));
        ratings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratings.setMaximumSize(new java.awt.Dimension(270, 60));
        ratings.setMinimumSize(new java.awt.Dimension(270, 60));
        ratings.setPreferredSize(new java.awt.Dimension(270, 60));
        Informationdialogbox.getContentPane().add(ratings, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 300, 80));

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 36)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doalog.jpg"))); // NOI18N
        jLabel9.setText("jLabel6");
        jLabel9.setMaximumSize(new java.awt.Dimension(896, 470));
        jLabel9.setMinimumSize(new java.awt.Dimension(896, 470));
        jLabel9.setPreferredSize(new java.awt.Dimension(896, 470));
        Informationdialogbox.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 896, 470));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel7.setText("7 Course");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 140, 20));

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel6.setText("Subway");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 50, 20));

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel4.setText("Tilak's Chocolady");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 110, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel3.setText("Bombay Street Cafe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 130, 20));

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel5.setText("Kafe Kulture");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 90, 20));

        cafekultur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foods copy.png"))); // NOI18N
        cafekultur.setBorderPainted(false);
        cafekultur.setContentAreaFilled(false);
        cafekultur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafekulturActionPerformed(evt);
            }
        });
        getContentPane().add(cafekultur, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 30, 20));

        rollsmania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foods copy.png"))); // NOI18N
        rollsmania.setBorderPainted(false);
        rollsmania.setContentAreaFilled(false);
        rollsmania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollsmaniaActionPerformed(evt);
            }
        });
        getContentPane().add(rollsmania, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 30, 20));

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel2.setText("Roll's Mania");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 140, 20));

        bombaystrtcafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foods copy.png"))); // NOI18N
        bombaystrtcafe.setBorderPainted(false);
        bombaystrtcafe.setContentAreaFilled(false);
        bombaystrtcafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bombaystrtcafeActionPerformed(evt);
            }
        });
        getContentPane().add(bombaystrtcafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 30, 20));

        chocolady.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foods copy.png"))); // NOI18N
        chocolady.setBorderPainted(false);
        chocolady.setContentAreaFilled(false);
        chocolady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocoladyActionPerformed(evt);
            }
        });
        getContentPane().add(chocolady, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 30, 20));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jButton1.setText("Return To Home Screen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, -1));

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jButton2.setText("FIND MOVIE THEATERS IN THIS AREA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        subway.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foods copy.png"))); // NOI18N
        subway.setBorderPainted(false);
        subway.setContentAreaFilled(false);
        subway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subwayActionPerformed(evt);
            }
        });
        getContentPane().add(subway, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 30, 20));

        sevencourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foods copy.png"))); // NOI18N
        sevencourse.setBorderPainted(false);
        sevencourse.setContentAreaFilled(false);
        sevencourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevencourseActionPerformed(evt);
            }
        });
        getContentPane().add(sevencourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 30, 20));

        settingbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        settingbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/107568.gif"))); // NOI18N
        settingbutton.setText("SETTINGS");
        settingbutton.setToolTipText("");
        settingbutton.setActionCommand("ACCOUNT SETTINGS");
        settingbutton.setAutoscrolls(true);
        settingbutton.setContentAreaFilled(false);
        settingbutton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        settingbutton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/107568.gif"))); // NOI18N
        settingbutton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/10nomap.jpg"))); // NOI18N
        settingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(settingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 120, -1));

        chocoladi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gulmoharfoodmap.png"))); // NOI18N
        getContentPane().add(chocoladi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 896, 470));

        rollsmania1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foods copy.png"))); // NOI18N
        rollsmania1.setBorderPainted(false);
        rollsmania1.setContentAreaFilled(false);
        rollsmania1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollsmania1ActionPerformed(evt);
            }
        });
        getContentPane().add(rollsmania1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 30, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chocoladyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocoladyActionPerformed
        // TODO add your handling code here:
        Informationdialogbox.setVisible(true);
        Informationdialogbox.setBounds(896,0,896,470);
        Informationdialogbox.setLocationRelativeTo(null);
        control = "chocolady";
    }//GEN-LAST:event_chocoladyActionPerformed

    private void rollsmaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollsmaniaActionPerformed
        // TODO add your handling code here:
        Informationdialogbox.setVisible(true);
        Informationdialogbox.setBounds(896,0,896,470);
        Informationdialogbox.setLocationRelativeTo(null);
        control = "rollsmania";
    }//GEN-LAST:event_rollsmaniaActionPerformed

    private void bombaystrtcafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bombaystrtcafeActionPerformed
        // TODO add your handling code here:
        Informationdialogbox.setVisible(true);
        Informationdialogbox.setBounds(896,0,896,470);
        Informationdialogbox.setLocationRelativeTo(null);
        control = "bombaystrtcafe";
    }//GEN-LAST:event_bombaystrtcafeActionPerformed

    private void cafekulturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafekulturActionPerformed
        // TODO add your handling code here:
        Informationdialogbox.setVisible(true);
        Informationdialogbox.setBounds(896,0,896,470);
        Informationdialogbox.setLocationRelativeTo(null);
        control = "cafekultur";
    }//GEN-LAST:event_cafekulturActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    gulmoharmovie gulmoharmovie = new gulmoharmovie();
    gulmoharfood.this.setVisible(false);
    gulmoharmovie.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    intro_page intro_page = new intro_page();
    gulmoharfood.this.setVisible(false);
    intro_page.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subwayActionPerformed
        // TODO add your handling code here:
        Informationdialogbox.setVisible(true);
        Informationdialogbox.setBounds(896,0,896,470);
        Informationdialogbox.setLocationRelativeTo(null);
        control = "subway";
    }//GEN-LAST:event_subwayActionPerformed

    private void sevencourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevencourseActionPerformed
        // TODO add your handling code here:
        Informationdialogbox.setVisible(true);
        Informationdialogbox.setBounds(896,0,896,470);
        Informationdialogbox.setLocationRelativeTo(null);
        control = "sevencourse";
    }//GEN-LAST:event_sevencourseActionPerformed

    private void rollsmania1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollsmania1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollsmania1ActionPerformed

    private void InformationdialogboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InformationdialogboxFocusGained
        // TODO add your handling code here:
        String query = null;
        if(null != control)
        switch (control) {
            case "chocolady":
            query = "select * FROM gulmohar where place = 'Tilaks Chocolady Bakery & Restaurant';";
            break;
            case "rollsmania":
            query = "select * FROM gulmohar where place = 'Rolls Mania';";
            break;
            case "bombaystrtcafe":
            query = "select * FROM gulmohar where place = 'Bombay Street Cafe';";
            break;
            case "subway":
            query = "select * FROM gulmohar where place = 'Subway';";
            break;
            case "cafekultur":
            query = "select * FROM gulmohar where place = 'Kafe Kulture';";
            break;
            case "sevencourse":
            query = "select * FROM gulmohar where place = '7 Course';";
            break;
            default:
            break;
        }

        try{
            //Connect to MYSQL Database
            Connection conn= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/locate_io", "root", "tiger");
            //Execute Query
            Statement stmt=conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            //We Get The Data
            while(rs.next())
            {
                String costfor2 = rs.getString("Cost_for_two");
                String phone_no = rs.getString("phone_no");
                String Address = rs.getString("Address");
                String Rating = rs.getString("Rating");
                cf2.setText("Rs. "+costfor2);
                phno.setText(""+phone_no);
                address.setText("<html><p><center>"+Address+"</center></p></html>");
                ratings.setText(""+Rating+"⋆");  //Special Character ⋆
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_InformationdialogboxFocusGained

    private void settingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingbuttonActionPerformed
        // TODO add your handling code here:
        Settings Settings = new Settings();
        gulmoharfood.this.setVisible(false);
        Settings.setLocationRelativeTo(null);
        Settings.setVisible(true);
    }//GEN-LAST:event_settingbuttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gulmoharfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gulmoharfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gulmoharfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gulmoharfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gulmoharfood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Informationdialogbox;
    private javax.swing.JLabel address;
    private javax.swing.JButton bombaystrtcafe;
    private javax.swing.JButton cafekultur;
    private javax.swing.JLabel cf2;
    private javax.swing.JLabel chocoladi;
    private javax.swing.JButton chocolady;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel phno;
    private javax.swing.JLabel ratings;
    private javax.swing.JButton rollsmania;
    private javax.swing.JButton rollsmania1;
    private javax.swing.JButton settingbutton;
    private javax.swing.JButton sevencourse;
    private javax.swing.JButton subway;
    // End of variables declaration//GEN-END:variables
}
