/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nayansaxena
 */
public class intro_page extends javax.swing.JFrame {

    /**
     * Creates new form intro_page
     */
    public intro_page() {
        initComponents();
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        movies_button1 = new javax.swing.JButton();
        food_button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        settingbutton.setForeground(new java.awt.Color(255, 255, 255));
        settingbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/107568.gif"))); // NOI18N
        settingbutton.setText("SETTINGS");
        settingbutton.setToolTipText("");
        settingbutton.setActionCommand("ACCOUNT SETTINGS");
        settingbutton.setAutoscrolls(true);
        settingbutton.setContentAreaFilled(false);
        settingbutton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        settingbutton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/107568.gif"))); // NOI18N
        settingbutton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/10nomap.jpg"))); // NOI18N
        settingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(settingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intro_page.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 480));

        movies_button1.setToolTipText("");
        movies_button1.setAlignmentY(0.0F);
        movies_button1.setBorderPainted(false);
        movies_button1.setContentAreaFilled(false);
        movies_button1.setFocusPainted(false);
        movies_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movies_button1ActionPerformed(evt);
            }
        });
        getContentPane().add(movies_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 450, 460));

        food_button2.setToolTipText("");
        food_button2.setAlignmentY(0.0F);
        food_button2.setBorderPainted(false);
        food_button2.setContentAreaFilled(false);
        food_button2.setFocusPainted(false);
        food_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_button2ActionPerformed(evt);
            }
        });
        getContentPane().add(food_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 4, 440, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void movies_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movies_button1ActionPerformed
        // TODO add your handling code here:
    Movie_Locality Movie_Locality = new Movie_Locality();
    intro_page.this.setVisible(false);
    Movie_Locality.setVisible(true);
    }//GEN-LAST:event_movies_button1ActionPerformed

    private void food_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_button2ActionPerformed
        // TODO add your handling code here:
    Food_Locality Locality = new Food_Locality();
    intro_page.this.setVisible(false);
    Locality.setVisible(true);
    }//GEN-LAST:event_food_button2ActionPerformed

    private void settingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingbuttonActionPerformed
        // TODO add your handling code here:
        Settings Settings = new Settings();
        intro_page.this.setVisible(false);
        Settings.setLocationRelativeTo(null);
        Settings.setVisible(true);
   
    }//GEN-LAST:event_settingbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intro_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intro_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intro_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intro_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intro_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton food_button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton movies_button1;
    private javax.swing.JButton settingbutton;
    // End of variables declaration//GEN-END:variables
}
