/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author nayansaxena
 */

public class Login extends javax.swing.JFrame {
PreparedStatement pst=null;
ResultSet rs=null;



    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPasswordField();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        backgrounfimagelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 284, 160, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 244, 160, -1));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 344, 130, 60));

        jLabel2.setFont(new java.awt.Font("Futura", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Don't have an account ?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 240, -1));

        signup.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 0, 0));
        signup.setText("Click Here to Sign Up !");
        signup.setAlignmentY(0.0F);
        signup.setBorderPainted(false);
        signup.setContentAreaFilled(false);
        signup.setFocusPainted(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 270, 20));

        backgrounfimagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.jpg"))); // NOI18N
        getContentPane().add(backgrounfimagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   //Write code to accept user entry and match with sql data.For Login Button-
   String uname=id.getText();
   String pwd=new String(password.getPassword());   
   variables var=new variables();
  
   try
   {
       Connection conn= (Connection)
               DriverManager.getConnection("jdbc:mysql://localhost:3306/locate_io", "root", "tiger");
        Statement stmt=conn.createStatement();
       String query="Select Uname,Password FROM credentials where Uname=? and Password=?;";
       pst=conn.prepareStatement(query);
       pst.setString(1, uname);
       pst.setString(2, pwd);
       String query2="UPDATE credentials SET Login_Time=curtime() where Uname='"+uname+"';";
       String LLI="SELECT Login_Time from credentials where Uname='"+uname+"'";
       String MS="SELECT Joined_On from credentials where Uname='"+uname+"'";
       stmt.addBatch(query2);
       rs=pst.executeQuery();
         if(uname.equals("")|| pwd.equals("")){
                                   
                                   JOptionPane.showMessageDialog(null," Missing Username or Password","Error",JOptionPane.ERROR_MESSAGE);
                                   return;
                                }
         if(uname!=("") & pwd!=("")) //else insert query is run properly
         {                     
       if(rs.next())
       {      
           final JDialog dialog = new JDialog();
           dialog.setAlwaysOnTop(true);    
           JOptionPane.showMessageDialog(dialog, "Welcome!");
           intro_page intro_page = new intro_page();
           Login.this.setVisible(false);
           intro_page.setVisible(true);
           
           var.user=uname;
           var.pas=pwd;
        }
       else
       {
           JOptionPane.showMessageDialog((Login)null, "Invalid Credentials!");
           
       }
       ResultSet rs2=stmt.executeQuery(LLI);
       if(rs2.last())
       {
           var.last=rs2.getString("Login_Time");
       }
       ResultSet rs3=stmt.executeQuery(MS);
       if(rs3.last())
       {
           var.mems=rs3.getString("Joined_On");
       }
       stmt.executeBatch();
         }
   }
   catch (Exception e)
   {
       JOptionPane.showMessageDialog((Login)null, e.getMessage());       
   }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
    //Write code to open signup jframe.For signup button-
    signup  signup = new  signup();
    Login.this.setVisible(false);
    signup.setVisible(true);
    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrounfimagelabel;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
