/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nayansaxena
 */
public class Movie_Locality extends javax.swing.JFrame {

    /**
     * Creates new form Food_Locality
     */
    public Movie_Locality() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        movie_oldcity = new javax.swing.JButton();
        movie_mpnagar = new javax.swing.JButton();
        movie_gulmohar = new javax.swing.JButton();
        movie_10no = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/location.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        movie_oldcity.setToolTipText("");
        movie_oldcity.setAlignmentY(0.0F);
        movie_oldcity.setBorderPainted(false);
        movie_oldcity.setContentAreaFilled(false);
        movie_oldcity.setFocusPainted(false);
        movie_oldcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_oldcityActionPerformed(evt);
            }
        });
        getContentPane().add(movie_oldcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 390, 180));

        movie_mpnagar.setToolTipText("");
        movie_mpnagar.setAlignmentY(0.0F);
        movie_mpnagar.setBorderPainted(false);
        movie_mpnagar.setContentAreaFilled(false);
        movie_mpnagar.setFocusPainted(false);
        movie_mpnagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_mpnagarActionPerformed(evt);
            }
        });
        getContentPane().add(movie_mpnagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 170));

        movie_gulmohar.setToolTipText("");
        movie_gulmohar.setAlignmentY(0.0F);
        movie_gulmohar.setBorderPainted(false);
        movie_gulmohar.setContentAreaFilled(false);
        movie_gulmohar.setFocusPainted(false);
        movie_gulmohar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_gulmoharActionPerformed(evt);
            }
        });
        getContentPane().add(movie_gulmohar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 410, 170));

        movie_10no.setToolTipText("");
        movie_10no.setAlignmentY(0.0F);
        movie_10no.setBorderPainted(false);
        movie_10no.setContentAreaFilled(false);
        movie_10no.setFocusPainted(false);
        movie_10no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_10noActionPerformed(evt);
            }
        });
        getContentPane().add(movie_10no, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 370, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void movie_oldcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_oldcityActionPerformed
        // TODO add your handling code here:
    Oldcitymovie  Oldcitymovie = new  Oldcitymovie();
    Movie_Locality.this.setVisible(false);
    Oldcitymovie.setVisible(true);
    
        

    }//GEN-LAST:event_movie_oldcityActionPerformed

    private void movie_mpnagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_mpnagarActionPerformed
        // TODO add your handling code here:
        mpnagmovie  mpnagmovie = new  mpnagmovie();
    Movie_Locality.this.setVisible(false);
    mpnagmovie.setVisible(true);
    }//GEN-LAST:event_movie_mpnagarActionPerformed

    private void movie_gulmoharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_gulmoharActionPerformed
        // TODO add your handling code here:
        gulmoharmovie  gulmoharmovie = new  gulmoharmovie();
    Movie_Locality.this.setVisible(false);
    gulmoharmovie.setVisible(true);
    }//GEN-LAST:event_movie_gulmoharActionPerformed

    private void movie_10noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_10noActionPerformed
        // TODO add your handling code here:
        dusnomovie  dusnomovie = new  dusnomovie();
    Movie_Locality.this.setVisible(false);
    dusnomovie.setVisible(true);
    }//GEN-LAST:event_movie_10noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food_Locality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movie_Locality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton movie_10no;
    private javax.swing.JButton movie_gulmohar;
    private javax.swing.JButton movie_mpnagar;
    private javax.swing.JButton movie_oldcity;
    // End of variables declaration//GEN-END:variables
}
