
import java.sql.*;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nayansaxena
 */


public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    
    
    public String query1="", query2="";
    public Settings() {
        initComponents();
     
        variables var=new variables();
        username.setText(""+var.user);
        password.setText(""+var.pas);
        lli.setText(""+var.last);
        memsince.setText(""+var.mems);
        
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Passwordprompt = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        paswd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NewUsername = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        newuname = new javax.swing.JTextField();
        updateuname = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        newpwd = new javax.swing.JPasswordField();
        updatepwd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        memsince = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        Passwordprompt.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTER PASSWORD");
        Passwordprompt.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, 30));

        paswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paswdActionPerformed(evt);
            }
        });
        Passwordprompt.getContentPane().add(paswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, -1));

        jButton1.setText("Done !");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Passwordprompt.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/granite_wall_2-wallpaper-1920x1080.jpg"))); // NOI18N
        Passwordprompt.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 530, 300));

        NewUsername.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ENTER NEW USERNAME");
        NewUsername.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 310, 30));
        NewUsername.getContentPane().add(newuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, -1));

        updateuname.setText("Done !");
        updateuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateunameActionPerformed(evt);
            }
        });
        NewUsername.getContentPane().add(updateuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/granite_wall_2-wallpaper-1920x1080.jpg"))); // NOI18N
        NewUsername.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 530, 300));

        NewPassword.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ENTER NEW PASSWORD");
        NewPassword.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 300, 30));

        newpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpwdActionPerformed(evt);
            }
        });
        NewPassword.getContentPane().add(newpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, -1));

        updatepwd.setText("Done !");
        updatepwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepwdActionPerformed(evt);
            }
        });
        NewPassword.getContentPane().add(updatepwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/granite_wall_2-wallpaper-1920x1080.jpg"))); // NOI18N
        NewPassword.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 530, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setEditable(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 180, -1));

        password.setEditable(false);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 180, 20));

        memsince.setEditable(false);
        memsince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memsinceActionPerformed(evt);
            }
        });
        getContentPane().add(memsince, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 180, -1));

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jButton3.setText("Delete Account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 140, -1));

        jButton5.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jButton5.setText("Return To Home Screen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 170, 30));

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jButton2.setText("Change Username");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jButton4.setText("Change Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        lli.setEditable(false);
        lli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lliActionPerformed(evt);
            }
        });
        getContentPane().add(lli, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSA.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void lliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lliActionPerformed

    private void memsinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memsinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memsinceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:  
        variables var=new variables();
        var.no=1;
         Passwordprompt.setVisible(true);
        Passwordprompt.setBounds(525,0,525,300);
        Passwordprompt.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void paswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paswdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        variables var=new variables();
        var.no=3;
         Passwordprompt.setVisible(true);
        Passwordprompt.setBounds(525,0,525,300);
        Passwordprompt.setLocationRelativeTo(null);
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        variables var=new variables();
        var.no=2;
         Passwordprompt.setVisible(true);
        Passwordprompt.setBounds(525,0,525,300);
        Passwordprompt.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void newpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpwdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        variables var=new variables();
        var.VerPass=paswd.getText();
        var.user=username.getText();
        
        if(var.VerPass.equals(password.getText()))
        {
    
       //Below lines only to be executed if PASSWORD OF USER IS CORRECT 
       //Below lines only to be executed if PASSWORD OF USER IS CORRECT 
       //ADD IF CONDITION TO CHECK CORRECTNESS OF PASSWORD AND THEN INCLUDE THE BELOW LINES IN IF CONDITION OF "IF PASSWORD IS CORRECT"
          
     paswd.setText("");
     Passwordprompt.setVisible(false);
        if(var.no==1){
        NewUsername.setVisible(true);
        NewUsername.setBounds(525,0,525,300);
        NewUsername.setLocationRelativeTo(null);
       System.out.println("New Username Is Being Added");
       
       
        }
        
        else if(var.no==2){
        NewPassword.setVisible(true);
        NewPassword.setBounds(525,0,525,300);
        NewPassword.setLocationRelativeTo(null);
        System.out.println("New Password Is Being Added");
        }
        
        else if(var.no==3){
           //ENTER CODE HERE TO DELETE ACCOUNT::::
           { 
            try{
        //Connect to MYSQL Database
          Connection conn= (Connection)
               DriverManager.getConnection("jdbc:mysql://localhost:3306/locate_io", "root", "tiger");
       //Execute Query
       Statement stmt=conn.createStatement();
        query1="DELETE from credentials where Uname='"+var.user+"' and Password='"+var.VerPass+"';";
        query2="DELETE from credentials_bak where Uname='"+var.user+"' and Password='"+var.VerPass+"';";        
       stmt.addBatch(query1);
       stmt.addBatch(query2);
       stmt.executeBatch();
        System.out.println("DELETION TAKING PLACE");
       
 JOptionPane.showMessageDialog(this, "Account deleted succesfully!");
       
       
     }
    catch(Exception e)
     {
        JOptionPane.showMessageDialog(this, e.getMessage());
     }
            
     }
           //Redirects to welcome jframe.
     {
        Welcome wel= new  Welcome();
  Settings.this.setVisible(false);
  wel.setVisible(true);
     }
     }  
  //ABOVE LINES ONLY TO BE EXECUTED IF PASSWORD IS CORRECT
    //ABOVE LINES ONLY TO BE EXECUTED IF PASSWORD IS CORRECT
      //ABOVE LINES ONLY TO BE EXECUTED IF PASSWORD IS CORRECT
        }
        else JOptionPane.showMessageDialog(this, "Please enter the correct password!");
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateunameActionPerformed
        // TODO add your handling code here:
        variables var= new variables();
        var.user=newuname.getText();
        
        NewUsername.setVisible(false);
    
        
        //ENTER CODE BELOW TO SAVE NEW USERNAME IN SQL TABLE::::::
        try{
        //Connect to MYSQL Database
          Connection conn= (Connection)
               DriverManager.getConnection("jdbc:mysql://localhost:3306/locate_io", "root", "tiger");
       //Execute Query
       Statement stmt=conn.createStatement();
        query1="UPDATE credentials set Uname='"+newuname.getText()+"' where Password='"+var.VerPass+"';";
        query2="UPDATE credentials_bak set Uname='"+newuname.getText()+"' where Password='"+var.VerPass+"';";        
       stmt.addBatch(query1);
       stmt.addBatch(query2);
       stmt.executeBatch();
              intro_page intro= new  intro_page();
   

           NewUsername.setVisible(false);
           JOptionPane.showMessageDialog(this, "Username changed succesfully!");
       
          Settings.this.setVisible(false);
 
  
  newuname.setText("");
        intro.setVisible(true);
       
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
        
        
       
        
        
    
        
    }//GEN-LAST:event_updateunameActionPerformed

    private void updatepwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepwdActionPerformed
        // TODO add your handling code here:
        variables var= new variables();
        var.pas=newpwd.getText();
        
       NewPassword.setVisible(false);

        //ENTER CODE BELOW TO SAVE NEW PASSWORD IN SQL TABLE
        try{
        //Connect to MYSQL Database
          Connection conn= (Connection)
               DriverManager.getConnection("jdbc:mysql://localhost:3306/locate_io", "root", "tiger");
       //Execute Query
       Statement stmt=conn.createStatement();
        query1="UPDATE credentials set Password='"+var.pas+"' where Password='"+var.VerPass+"';";
        query2="UPDATE credentials_bak set Password='"+var.pas+"' where Password='"+var.VerPass+"';";              
       stmt.addBatch(query1);
       stmt.addBatch(query2);
       stmt.executeBatch();
       intro_page intro=new intro_page();
         
 
        
           NewPassword.setVisible(false);
            
 
 
       JOptionPane.showMessageDialog(this, "Password changed succesfully!"); 
       
       Settings.this.setVisible(false);
        newpwd.setText("");
   intro.setVisible(true);
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
        
        
        
        
    }//GEN-LAST:event_updatepwdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        intro_page intro_page = new intro_page();
       Settings.this.setVisible(false);
        intro_page.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog NewPassword;
    private javax.swing.JDialog NewUsername;
    private javax.swing.JDialog Passwordprompt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lli;
    private javax.swing.JTextField memsince;
    private javax.swing.JPasswordField newpwd;
    private javax.swing.JTextField newuname;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField paswd;
    private javax.swing.JButton updatepwd;
    private javax.swing.JButton updateuname;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
